// <auto-generated />
using System;
using JuegoPruebaTecnica.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace JuegoPruebaTecnica.Migrations
{
    [DbContext(typeof(LocaldbContext))]
    [Migration("20240831134846_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("JuegoPruebaTecnica.Models.Jugador", b =>
                {
                    b.Property<int>("IdJugador")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdJugador"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("IdJugador")
                        .HasName("PK__Jugador__99E32016D4D44748");

                    b.ToTable("Jugador", (string)null);
                });

            modelBuilder.Entity("JuegoPruebaTecnica.Models.Movimiento", b =>
                {
                    b.Property<int>("IdMovimiento")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdMovimiento"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<bool>("Gano")
                        .HasColumnType("bit");

                    b.Property<int>("IdJugador")
                        .HasColumnType("int");

                    b.Property<int>("IdPartida")
                        .HasColumnType("int");

                    b.HasKey("IdMovimiento")
                        .HasName("PK__Movimien__881A6AE081A980D3");

                    b.HasIndex("IdJugador");

                    b.HasIndex("IdPartida");

                    b.ToTable("Movimiento", (string)null);
                });

            modelBuilder.Entity("JuegoPruebaTecnica.Models.Partida", b =>
                {
                    b.Property<int>("IdPartida")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdPartida"));

                    b.Property<int?>("IdGanador")
                        .HasColumnType("int");

                    b.HasKey("IdPartida")
                        .HasName("PK__Partida__6ED660C70B4423B7");

                    b.HasIndex("IdGanador");

                    b.ToTable("Partidas");
                });

            modelBuilder.Entity("JuegoPruebaTecnica.Models.Movimiento", b =>
                {
                    b.HasOne("JuegoPruebaTecnica.Models.Jugador", "IdJugadorNavigation")
                        .WithMany("Movimientos")
                        .HasForeignKey("IdJugador")
                        .IsRequired()
                        .HasConstraintName("FK__Movimient__IdJug__4E88ABD4");

                    b.HasOne("JuegoPruebaTecnica.Models.Partida", "IdPartidaNavigation")
                        .WithMany("Movimientos")
                        .HasForeignKey("IdPartida")
                        .IsRequired()
                        .HasConstraintName("FK__Movimient__IdPar__4F7CD00D");

                    b.Navigation("IdJugadorNavigation");

                    b.Navigation("IdPartidaNavigation");
                });

            modelBuilder.Entity("JuegoPruebaTecnica.Models.Partida", b =>
                {
                    b.HasOne("JuegoPruebaTecnica.Models.Jugador", "IdGanadorNavigation")
                        .WithMany("Partidas")
                        .HasForeignKey("IdGanador")
                        .HasConstraintName("FK__Partida__IdGanad__4BAC3F29");

                    b.Navigation("IdGanadorNavigation");
                });

            modelBuilder.Entity("JuegoPruebaTecnica.Models.Jugador", b =>
                {
                    b.Navigation("Movimientos");

                    b.Navigation("Partidas");
                });

            modelBuilder.Entity("JuegoPruebaTecnica.Models.Partida", b =>
                {
                    b.Navigation("Movimientos");
                });
#pragma warning restore 612, 618
        }
    }
}
